language: go

go:
  - 1.10.x
  - 1.11.x
  - master
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - go test -cover ./...