title 					= "Credit Card Validation API Config File"

[http]
host 					= 8080 # local port.
access_log_path 	    = "access.log" # location of access.log file
error_log_path 	        = "error.log" # location of error.log file
card_types_path 		= "card_types.json" # location of card types .json file
